// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class CarScanEvent implements flatbuffers.IUnpackableObject<CarScanEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CarScanEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCarScanEvent(bb:flatbuffers.ByteBuffer, obj?:CarScanEvent):CarScanEvent {
  return (obj || new CarScanEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCarScanEvent(bb:flatbuffers.ByteBuffer, obj?:CarScanEvent):CarScanEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CarScanEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

address():string|null
address(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
address(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startCarScanEvent(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addAddress(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, addressOffset, 0);
}

static endCarScanEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCarScanEvent(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, addressOffset:flatbuffers.Offset):flatbuffers.Offset {
  CarScanEvent.startCarScanEvent(builder);
  CarScanEvent.addName(builder, nameOffset);
  CarScanEvent.addAddress(builder, addressOffset);
  return CarScanEvent.endCarScanEvent(builder);
}

unpack(): CarScanEventT {
  return new CarScanEventT(
    this.name(),
    this.address()
  );
}


unpackTo(_o: CarScanEventT): void {
  _o.name = this.name();
  _o.address = this.address();
}
}

export class CarScanEventT implements flatbuffers.IGeneratedObject {
constructor(
  public name: string|Uint8Array|null = null,
  public address: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const address = (this.address !== null ? builder.createString(this.address!) : 0);

  return CarScanEvent.createCarScanEvent(builder,
    name,
    address
  );
}
}
